def name(L):
  if L == "A":
    print("    A")
    print("  A   A ")
    print("A       A")
    print("A A A A A")
    print("A       A") 
    print("A       A") 
    print("A       A") 
  elif L == "B":
    print("B B B B")
    print("B       B")
    print("B       B")
    print("B B B B")
    print("B       B")
    print("B       B")
    print("B B B B")
  elif L == "C":
    print("  C C C  ")
    print("C       C")
    print("C")
    print("C")
    print("C")
    print("C       C")
    print("  C C C  ")
  elif L == "D":
    print("D D D D ")
    print("D       D")
    print("D       D")
    print("D       D")
    print("D       D")
    print("D       D")
    print("D D D D ")
  elif L == "E":
    print("E E E E E")
    print("E")
    print("E")
    print("E E E")
    print("E")
    print("E")
    print("E E E E E")
  elif L == "F":
    print("F F F F F")
    print("F")
    print("F")
    print("F F F")
    print("F")
    print("F")
    print("F")
  elif L == "G":
    print("  G G G")
    print("G       G")
    print("G")
    print("G G G G G")
    print("G       G")
    print("G       G")
    print("  G G G ")
  elif L == "H":
    print("H       H")
    print("H       H")
    print("H       H")
    print("H H H H H")
    print("H       H")
    print("H       H")
    print("H       H")
  elif L == "I":
    print("I I I I I")
    print("    I")
    print("    I")
    print("    I")
    print("    I")
    print("    I")
    print("I I I I I")
  elif L == "J":
    print("J J J J J")
    print("    J")
    print("    J")
    print("    J")
    print("J   J")
    print("J   J")
    print("  J J ")
  elif L == "K":
    print("K       K")
    print("K     K")
    print("K   K")
    print("K K")
    print("K   K")
    print("K     K")
    print("K       K")
  elif L == "L":
    print("L")
    print("L")
    print("L")
    print("L")
    print("L")
    print("L")
    print("L L L L L")
  elif L == "M":
    print("M       M")
    print("M M   M M")
    print("M M   M M")
    print("M   M   M")
    print("M       M")
    print("M       M")
    print("M       M")
  elif L == "N":
    print("N       N")
    print("N N     N")
    print("N   N   N")
    print("N     N N")
    print("N       N")
    print("N       N")
    print("N       N")
  elif L == "O":
    print("  O O O")
    print("O       O")
    print("O       O")
    print("O       O")
    print("O       O")
    print("O       O")
    print("  O O O")
  elif L == "P":
    print("P P P P")
    print("P       P")
    print("P       P")
    print("P P P P")
    print("P")
    print("P")
    print("P")
  elif L == "Q":
    print("  Q Q Q ")
    print("Q       Q")
    print("Q       Q")
    print("Q       Q")
    print("Q       Q")    
    print("Q     Q")
    print("  Q Q   Q")
  elif L == "R":
    print("R R R R")
    print("R       R")
    print("R       R")
    print("R R R R")
    print("R   R")
    print("R     R")
    print("R       R")
  elif L == "S":
    print("  S S S")
    print("S       S")
    print("S")
    print("  S S S")
    print("        S")
    print("S       S")
    print("  S S S")
  elif L == "T":
    print("T T T T T")
    print("    T")
    print("    T")
    print("    T")
    print("    T")
    print("    T")
    print("    T")
  elif L == "U":
    print("U       U")
    print("U       U")
    print("U       U")
    print("U       U")
    print("U       U")
    print("U       U")
    print("  U U U")
  elif L == "V":
    print("V       V")
    print("V       V")
    print("V       V")
    print("V       V")
    print("V       V")
    print("  V   V")
    print("    V")
  elif L == "W":
    print("W       W")
    print("W       W")
    print("W       W")
    print("W   W   W")
    print("W W   W W")
    print("W       W")
  elif L == "X":
    print("X       X")
    print("X       X")
    print("  X   X")
    print("    X")
    print("  X   X")
    print("X       X")
    print("X       X")
  elif L == "Y":
    print("Y       Y")
    print("  Y   Y")
    print("    Y")
    print("    Y")
    print("    Y")
    print("    Y")
    print("    Y")
  elif L == "Z":
    print("Z Z Z Z Z")
    print("        Z")
    print("      Z")
    print("    Z")
    print("  Z")
    print("Z")
    print("Z Z Z Z Z")
  else:
    print(" ")
matn = input("matn kiriting: ").upper()
for i in range(0, len(matn)):
    name(matn[i])
    print()